### ISSUE TITLE
[Tangram R&D] Throw an exception when a ccss property is not supported

### ISSUE THREAD

**Issue by donflopez** [CartoDB/carto#22]
Allow pass a reference at instantiation time and throw an exception when CCSS is not valid with that reference.

ADDON: Testing the trigger exception, we've discovered that `Reference.setData` is setting the reference passed as a closure under at module level, if you have several references in different instances of Renderer they will use the latest reference setted

**Comment by alonsogarciapablo** [comment]
Is this ready for code review? This issue is not linked to any pull request...

**Comment by donflopez** [comment]
It needs revision by @rochoa because some strange tests are failing.

**Comment by donflopez** [comment]
New [PR](https://github.com/CartoDB/carto/pull/27)

**Comment by dgaubert** [comment]
CR: 🇨🇭

**Comment by dgaubert** [comment]
Hey, are there acceptance steps to follow?

**Comment by dgaubert** [comment]
BTW, I think automated tests implemented in [here](https://github.com/CartoDB/carto/pull/27) are valid as acceptance.

**Comment by donflopez** [comment]
Yes, the acceptance tests have to be use the library with another reference and try to make it fail, but as you said, the tests seems good enough!

**Comment by donflopez** [comment]
Should I merge this PR?
