### ISSUE TITLE
Ampersands on feature properties

### ISSUE THREAD

**Issue by dv343** [CartoDB/carto#43]
Original issue: https://github.com/CartoDB/support/issues/1032

I think that carto is not managing ampersands in a good way, particularly on the JS code generation. They are expanded to: `&amp`, but they should be left as-is, just `&`.

**Comment by dv343** [comment]
I've just checked that carto is the one who puts the 'amp' there.

**Comment by rafatower** [comment]
What's your plan for acceptance-testing this? thanks!

**Comment by dv343** [comment]
I've already tested it, and it doesn't work. We tested it on local before, and there it worked, but maybe because we mix the merged fix and another work-around that never was merged (but could have been present in local).

**Comment by dv343** [comment]
Fixed with #45
